DO $$
DECLARE
  snusboksen_id UUID;
  jeg_har_aldri_id UUID;
  pekeleken_id UUID;
BEGIN

DELETE FROM kort WHERE spillpakke_id IN (SELECT id FROM spillpakker WHERE navn IN ('Snusboksen', 'Jeg har aldri', 'Pekeleken'));
DELETE FROM spillpakker WHERE navn IN ('Snusboksen', 'Jeg har aldri', 'Pekeleken');

INSERT INTO spillpakker (navn, beskrivelse, regler, farge, ikon, aktiv) VALUES (
  'Snusboksen',
  'Den klassiske snusboksen. Trekk et kort og gjør som det sier.',
  'Trekk ett kort per runde. Gjør det kortet sier, eller drikk dobbelt.',
  '#2D5A1B',
  'snusboks',
  true
) RETURNING id INTO snusboksen_id;

INSERT INTO spillpakker (navn, beskrivelse, regler, farge, ikon, aktiv) VALUES (
  'Jeg har aldri',
  'Klassikeren. Si noe du aldri har gjort – alle som har gjort det drikker.',
  'En spiller leser kortet høyt. Alle som HAR gjort det som står på kortet, drikker. Neste spiller leser neste kort.',
  '#C41E3A',
  'glass',
  true
) RETURNING id INTO jeg_har_aldri_id;

INSERT INTO spillpakker (navn, beskrivelse, regler, farge, ikon, aktiv) VALUES (
  'Pekeleken',
  'Pek på den som passer best. Flest pekefingre = drikk!',
  'Les kortet høyt. Alle peker samtidig på den i gruppen som passer best. Den som får flest pekefingre, drikker antall slurker som tilsvarer antall pekefingre de fikk.',
  '#FF6B35',
  'finger',
  true
) RETURNING id INTO pekeleken_id;

INSERT INTO kort (spillpakke_id, type, tittel, innhold) VALUES
  (snusboksen_id, 'utfordring', 'Utfordring', 'Si noe flatterende om {spiller} – eller drikk 2'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Ring den du helst ikke vil ringe akkurat nå – eller drikk 5'),
  (snusboksen_id, 'utfordring', 'Utfordring', '{spiller} må snakke med aksent i neste 3 runder – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Gjør 10 armhevinger – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Send en melding til en tilfeldig kontakt med bare emojis – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell den pinligste tingen du har gjort på fest – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', '{spiller} velger hvem du må kysse på kinnet – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Imiter noen i gruppen til de gjetter hvem det er – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Les de tre siste meldingene du sendte høyt – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Dans alene i 30 sekunder uten musikk – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Si noe du aldri har fortalt noen i gruppen – eller drikk 5'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Bytt en plagg med {spiller} for neste runde – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Ta et bilde og legg det ut på story – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell den verste løgnen du har fortalt foreldrene dine – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Gjør din beste stripping-dans i 15 sekunder – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'La {spiller} gå gjennom galleriet ditt i 30 sekunder – eller drikk 5'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Skriv en flørtetekst til {spiller} og les den høyt – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Gjør en stå-på-hendene-øvelse – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell noe du angrer på fra de siste 6 månedene – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Si tre ting du liker med {spiller} – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Bytt plass med {spiller1} og bli sittende der resten av runden – eller drikk 2'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om din første kjærlighet uten å si navnet – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Gjør en trustedfall mot {spiller} – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Vis den seneste søket ditt på nettet – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Lag en rap om {spiller} på 20 sekunder – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Del skjermen din og vis hva du har oppe akkurat nå – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Snakk uten å bruke bokstaven S i neste runde – eller drikk 3 hvis du feiler'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Si hva du egentlig tenker om {spiller}s stil – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Gjør 20 knebøy – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'La gruppa bestemme profilbilde ditt for neste 24 timer – eller drikk 5'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Sett på alarmen 06:00 i morgen – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om den gangen du var mest flau på jobb eller skole – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Ring en forelder og si "jeg har noe å fortelle deg" og legg på – eller drikk 5'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Vis den verste bidet av deg selv på telefonen – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Trekk frem en hemmelighet du tror ingen vet – eller drikk 5'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Gi {spiller} en hel rygg-massasje – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Ta en selfie med noen du ikke kjenner i rommet – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Beskriv drømmekjæresten din uten å si utseende – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Plystre en sang alle skal gjette – eller drikk 2'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell hva du liker minst med deg selv – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Lag en toast for {spiller} – vær ærlig, ikke bare søt – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Vis de 5 siste emnene du søkte på YouTube – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om en gang du ble tatt i løgn – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Gi {spiller} et kompliment du aldri har gitt noen – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om en drøm du har skammet deg over – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', '{spiller} bestemmer hva du drikker neste runde'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Gjør en yoga-pose og hold den i 30 sekunder – eller drikk 2'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om den verste daten du har vært på – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Send en hjerte-emoji til den siste du pratet med – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Si en ting du aldri har turte å si til {spiller} – eller drikk 5'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om den gangen du var mest sjalu – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Gjør klovnenese med tommel og si en vits – eller drikk 2'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell hva du ville gjort med 1 million kroner – du har 30 sekunder'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Si noe pinlig du har gjort alene hjemme – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Beskriv {spiller} med bare 3 ord – de får bestemme om du drikker'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell hvem i gruppen du tror er best i sengen – eller drikk 5'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Vis den mest pinlige appen på telefonen – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om en gang du snuste på noen (romantisk) – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Bjeffe som en hund i 10 sekunder – eller drikk 2'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om den verste råda du har gitt noen – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Ta et bilde av det styggeste i rommet og send til mamma – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Si noe genuint snilt om alle i gruppen, ett av gangen – eller drikk'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om den verste jobben du har hatt – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Gjør planken i 45 sekunder – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'La {spiller} lese en tilfeldig chat du har på telefonen – eller drikk 5'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om noe du har gjort som du helst vil glemme – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Beskriv den verste luktopplevelsen din – eller drikk 2'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Prøv å kysse albuen din – eller drikk 2'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell hvem du er mest sjalu på akkurat nå – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Skriv en falsk anmeldelse av {spiller} som restaurant – les den høyt'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Snakk som en robot i neste to runder – eller drikk 3 hvis du feiler'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om noe du ønsker du hadde gjort annerledes i forrige forhold – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Gjør et headstand mot veggen i 10 sekunder – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om en hemmelighet du har holdt for en venn – eller drikk 5'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Si det peinligste du noen gang har sagt til en du likte – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om den gangen du var mest redd – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', '{spiller} og {spiller1} bytter glass for resten av runden'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om den siste gangen du gråt – ekte eller film – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Vis lockscreen-bakgrunnen din og forklar hvorfor du valgte den'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om det rareste du har spist – eller drikk 2'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Si en ting du misunner {spiller} – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om en gang du brøt en løfte – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Imiter favorittlæreren din – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell hva du tenker på rett før du sovner – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Gjør en fugl-dans i 15 sekunder – eller drikk 2'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om den siste gangen noen flørtet med deg – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', '{spiller} velger en utfordring til deg på 10 sekunder'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell hva du ville sagt til deg selv for 5 år siden – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Lag en kompliment-rap om {spiller} i 20 sekunder'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om en gang du var utrolig uheldig – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Legg hodet i fanget på {spiller} i neste runde – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om en gang du løy for å komme deg ut av noe – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Gi {spiller} en high-five og si "du er fantastisk"'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om det mest spontane du har gjort – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Si noe du har grublet over den siste uken – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om en gang du var ekstremt klønete – eller drikk 2'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Prøv å si "Svarte katter sitter på svarte matter" tre ganger raskt – eller drikk'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Beskriv {spiller} som et Tinder-profil på 30 sekunder'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om den dummeste impulskjøpet du har gjort – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Sett på et tilfeldig nummer i kontaktlisten og vis hvem det er – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om en gang du stalket noen på sosiale medier – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Si en sannhet gruppa sikkert ikke vet om deg – eller drikk 5'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell hva du synes er overratet i livet – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Gjør en worm på gulvet – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om noe du gjemmer for foreldrene dine – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'La {spiller} velge ny profilbilde på Facebook – eller drikk 5'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell hva du drømmer om om natten – bokstavelig talt – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Gjør en moonwalk over gulvet – eller drikk 2'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om den siste gangen du lo så mye du nesten gråt – eller drikk 2'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Si tre ting du gjør som ingen vet om – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om en gang du snodde deg unna ansvaret – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Synge første verset av en norsk barnesang – eller drikk 2'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Si hva du egentlig tenkte da du møtte {spiller} første gang – eller drikk 4'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om en gang noen overrasket deg positivt – eller drikk 2'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Kjøp {spiller} en drink – eller drikk to selv'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell din verste kjøkken-katastrofe – eller drikk 2'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Si noe du tror bare du vet om {spiller} – eller drikk 3'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har blitt blokkert av noen drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har sendt en melding de angret på drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har ringt eks''en sent på kvelden drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har jukset på en eksamen drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har gjort noe de skammer seg over på fest drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har løyet til sjefen sin drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har stalket en eks på Instagram drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har hatt en "one night stand" drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har sovet til over 12 i dag drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har sagt de var syke men egentlig bare ikke giddet drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har svindlet på en eksamen drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har hatt en crush på noen i rommet drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har gråt over en serie eller film den siste måneden drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har sletta meldinger de angret på å sende drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har logget inn på eks''ens Netflix etter bruddet drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har møtt noen fra datingapp drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Den som sist sendte en "tror du er glad i meg"-melding drikker 3'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som ikke husker noe fra sist gang de var på byen drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har tatt et bilde av maten sin og lagt det ut drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har gjort noe de angrer på etter for mange drinker drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har kommentert noe stygt på internett drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som fortsatt har uåpnede meldinger fra i dag drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har hatt følelser for en kompis drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har brukt over 1000 kr på en impulshandling drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har hatt drama med en venn om en person de likte drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har blitt for full på en jobbfest drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har en hemmelig Spotify-spilleliste drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har lest andres dagbok eller meldinger drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har "ghostet" noen drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har blitt "ghostet" drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har sagt "jeg er på vei" når de ikke en gang hadde startet å kle på seg drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har hatt en drøm om noen i rommet drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har laget mat full drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har googlet navnet sitt drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har sendt en melding til feil person drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har sovet i klærne fra kvelden før drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har sagt at de var hjemme men egentlig var ute drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har hatt en lang meldingstråd med noen de aldri møtte igjen drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har lånt penger og glemt å betale tilbake drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har ligget og scrollet i stedet for å sove drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har vært syk av for mye alkohol den siste måneden drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har smilt til noen de ikke liker drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har kjøpt noe dyrt og gjemt det for kjæresten drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har lest en bok bare for å virke interessant drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har stukket av fra en fest uten å si adjø drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har latt telefonen ringe uten å svare drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har søkt på en eks på LinkedIn drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har tatt en selfie og slettet den med en gang drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har spist mat som hadde gått ut på dato drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har blitt ertet for noe de sa på druk drikker'),
  (snusboksen_id, 'alle_drikker', 'Alle drikker', 'Alle som har dratt hjem fra en date tidligere enn planlagt drikker'),
  (snusboksen_id, 'regel', 'Regel', 'Fra nå av må alle drikke med venstre hånd – den som glemmer det, drikker 2 ekstra'),
  (snusboksen_id, 'regel', 'Regel', 'Ingen kan si ordet "drikke" – den som sier det, drikker 3'),
  (snusboksen_id, 'regel', 'Regel', '{spiller} er kongen/dronningen. Alle må adressere dem som "Deres Majestet" til neste kort'),
  (snusboksen_id, 'regel', 'Regel', 'Alle må tomle opp hver gang de drikker – den som glemmer, drikker dobbelt'),
  (snusboksen_id, 'regel', 'Regel', 'Ingen kan si "nei" til neste tre spørsmål – hva enn det er'),
  (snusboksen_id, 'regel', 'Regel', 'Alle må snakke i tredje person om seg selv til neste runde'),
  (snusboksen_id, 'regel', 'Regel', '{spiller} har "vannklosett-veto" – de kan sende hvem som helst for å hente drikke'),
  (snusboksen_id, 'regel', 'Regel', 'Alle må si "takk" hver gang de drikker – ellers drikker de igjen'),
  (snusboksen_id, 'regel', 'Regel', 'Ingen mobiltelefoner i neste 5 minutter – den som bryter regelen, drikker 3'),
  (snusboksen_id, 'regel', 'Regel', 'Alle må hviske til neste regel-kort trekkes'),
  (snusboksen_id, 'regel', 'Regel', '{spiller} lager en ny regel som gjelder til neste regel-kort trekkes'),
  (snusboksen_id, 'regel', 'Regel', 'Ingen kan peke med fingeren – bruk albuen. Den som glemmer, drikker 2'),
  (snusboksen_id, 'regel', 'Regel', 'Alle må klappe to ganger før de drikker – ellers drikker de igjen'),
  (snusboksen_id, 'regel', 'Regel', 'Den som ler først etter dette kortet, drikker 3'),
  (snusboksen_id, 'regel', 'Regel', '{spiller1} og {spiller} er drikke-partnere: hvis en drikker, drikker begge'),
  (snusboksen_id, 'kategori', 'Kategori', 'Gå rundt bordet: alle sier én ting de aldri ville gjort for 100 kr. Den som ikke klarer å si noe, drikker'),
  (snusboksen_id, 'kategori', 'Kategori', 'Gå rundt: alle nevner en norsk artistnavn. Den som ikke kommer på noen, drikker'),
  (snusboksen_id, 'kategori', 'Kategori', 'Alle sier én ting de hater med sosiale medier. Repetisjon = drikk'),
  (snusboksen_id, 'kategori', 'Kategori', 'Gå rundt: alle sier et land de aldri vil besøke og hvorfor. Ingen repetisjon – ellers drikk'),
  (snusboksen_id, 'kategori', 'Kategori', 'Alle nevner én ting de gjør som andre synes er irriterende. Den som ikke kommer på noe, drikker 3'),
  (snusboksen_id, 'kategori', 'Kategori', 'Gå rundt: alle nevner et Netflix-show de ikke har fullført. Repetisjon = drikk'),
  (snusboksen_id, 'kategori', 'Kategori', 'Alle sier én grunn til at de er single (eller var single). Den som ikke vil svare, drikker'),
  (snusboksen_id, 'kategori', 'Kategori', 'Gå rundt: alle sier et deal-breaker i et forhold. Repetisjon = drikk'),
  (snusboksen_id, 'kategori', 'Kategori', 'Alle nevner én ting de ville tatt med på en øde øy. Repetisjon = drikk'),
  (snusboksen_id, 'kategori', 'Kategori', 'Gå rundt: alle sier én ting de aldri innrømmer for foreldrene. Den som ikke svarer, drikker 4'),
  (snusboksen_id, 'pekelek', 'Pekelek', 'Hvem i gruppen ville overlevd en zombie-apokalypse? Den med flest pekefingre drikker'),
  (snusboksen_id, 'pekelek', 'Pekelek', 'Hvem ville mest sannsynlig ringt eks''en full i natt? Den med flest pekefingre drikker'),
  (snusboksen_id, 'pekelek', 'Pekelek', 'Hvem her er den beste kokken? Den med flest pekefingre drikker IKKE – alle andre drikker'),
  (snusboksen_id, 'pekelek', 'Pekelek', 'Hvem er mest sannsynlig å havne på forsiden av VG (for noe galt)? Den med flest pekefingre drikker'),
  (snusboksen_id, 'pekelek', 'Pekelek', 'Hvem er den mest dramatiske i gruppen? Den med flest pekefingre drikker'),
  (snusboksen_id, 'pekelek', 'Pekelek', 'Hvem ville vært best som politikker? Den med færrest pekefingre drikker'),
  (snusboksen_id, 'pekelek', 'Pekelek', 'Hvem er mest sannsynlig å glemme søppeldagen? Den med flest pekefingre drikker'),
  (snusboksen_id, 'pekelek', 'Pekelek', 'Hvem her ville klart seg lengst uten telefon? Den med færrest pekefingre drikker'),
  (snusboksen_id, 'pekelek', 'Pekelek', 'Hvem ville vært mest sannsynlig å gråte på bryllupsdagen? Den med flest pekefingre drikker'),
  (snusboksen_id, 'pekelek', 'Pekelek', 'Hvem ville vært verst som sjef? Den med flest pekefingre drikker'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell hva du savner mest med barndommen din – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Gjør en trylletrick – eller drikk 2'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell hvem i gruppen du ville ringt om du var i trøbbel klokken 3 om natten – uten å drikke'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Si noe du setter pris på ved kvelden akkurat nå – eller drikk 2'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell det morsomste som har skjedd deg i år – eller drikk 2'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Vis et bilde fra da du var liten – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om den beste gaven du noen gang har gitt noen – eller drikk 2'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Beskriv {spiller} som en superhelt – eller drikk 2'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om noe på listen din over ting du vil gjøre – eller drikk 2'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Si det siste du googlet – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell hvilken superevne du ville valgt og hvorfor – 30 sekunder'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Beskriv drømmeferien din i detalj – eller drikk 2'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell hvem du ville tatt med om du skulle reise alene – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Lag en sang om {spiller} på melodi av en norsk barnesang – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om det rareste du har funnet i en lomme – eller drikk 2'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Si noe du alltid har ønsket å lære deg – eller drikk 2'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om den beste maten du noen gang har spist – eller drikk 2'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Beskriv den perfekte søndagen uten å nevne telefonen – eller drikk 3'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Fortell om det kuleste stedet du har besøkt – eller drikk 2'),
  (snusboksen_id, 'utfordring', 'Utfordring', 'Si tre ord som beskriver kvelden så langt – eller drikk 2');

INSERT INTO kort (spillpakke_id, type, tittel, innhold) VALUES
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri sendt en melding til feil person'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri sovnet i en taxi'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri kysset noen jeg møtte samme kveld'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri løyet om alderen min'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri ringt eks''en sent på natten'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri jukset på en prøve eller eksamen'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri hatt et hemmelig forhold'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri stalket noen på sosiale medier'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri vært arrestert'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri løyet for å slippe å møte noen'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri hatt følelser for en venn av kjæresten min'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri delt en annens hemmelighet'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri vært på blind date'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri møtt noen fra Tinder eller annen datingapp'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri kastet opp av for mye alkohol'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri blitt kastet ut av et utested'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri tattovering'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri hoppet i havet midt på natten'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri stjålet noe (uansett hvor lite)'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri brukt en annens ID'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri ligget og late som jeg sov for å unngå noen'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri sendt en melding som en annen person'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri hatt en hemmelig crush på noen gift'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri sagt "jeg er på vei" og ikke vært det'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri lest dagboken til noen andre'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri lånt penger og ikke betalt tilbake'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri brutt en løfte med vilje'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri blitt forlatt'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri forlatt noen'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri gråt over en serie'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri sett på den samme filmen mer enn tre ganger'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri spist en hel pizza alene'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri glemt en viktig bursdag'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri brukt sykepenger når jeg egentlig var frisk'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri hatt en krangel med noen via melding'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri blitt forelska i en kompis sin kjæreste/kjæreste'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri gitt et falsk telefonnummer'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri gjort noe romantisk som gikk helt galt'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri blitt dumpa via melding'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri dumpet noen via melding'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri "ghostet" noen'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri blitt "ghostet"'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri tatt en selfie jeg slettet med en gang'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri bidratt til sladder jeg visste var usant'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri googlet navnet mitt'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri vært på et bryllup og tenkt "dette kommer ikke til å funke"'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri logget inn på en annens konto uten tillatelse'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri kjørt bil etter å ha drukket'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri lyget på CV''en min'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri sagt "jeg elsker deg" uten å mene det'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri fortalt noen at jeg ikke likte gaven deres (til ansiktet)'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri prøvd snus eller røyk'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri hopp-startet et fremmed land'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri kommet hjem i taxi uten å huske at jeg bestilte den'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri vunnet en konkurranse'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri vært med i et band eller fremtredelse på scenen'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri hatt en ekskjæreste som jeg angrer på å ha sluttet med'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri vært på ferie alene'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri prøvd å gjøre noe jeg så på YouTube og mislyktes totalt'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri sovet over hos noen jeg nettopp møtte'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri drukket alene hjemme (frivillig)'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri ringt feil person og hatt en lang samtale'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri angret på noe tatovering eller piercing'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri stukket av fra en fest uten å si adjø'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri glemt hva som skjedde kvelden før'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri kjøpt blomster til meg selv'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri giftet meg eller vært forlovet'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri blitt avvist av noen jeg likte'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri sagt noe stygt om noen og blitt tatt i det'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri prøvd å lage mat full og brent det'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri mistet en venn på grunn av et romantisk forhold'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri tatt feil buss eller tog og endt opp et annet sted'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri kjøpt noe dyrt og gjemt det for foreldrene'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri gitt en gave jeg selv hadde fått'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri gråt på en buss eller offentlig sted alene'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri sendt en "feil sendt"-melding med vilje'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri solgt noe på Finn.no'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri truffet en kjendis'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri holdt talen på et arrangement'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri skrevet et brev for hånd til noen'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri danset på et bord'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri hatt en lang diskusjon om politikk som endte galt'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri latt som jeg ikke så noen jeg kjente i butikken'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri sagt "ingenting" når jeg egentlig var sur'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri lagt ut noe på sosiale medier for å gjøre noen sjalu'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri nektet å svare på et spørsmål i en gruppe'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri lyst på en annen enn den jeg er med'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri betalt for noe med penger jeg ikke hadde'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri sett på noe jeg skammer meg over på internett'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri tatt sykkel, scooter eller bil som ikke var min'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri spist noe rart på en våger'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri hatt en hemmelig pengegjeld'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri blitt fortalt at jeg sover høyt'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri tatt en nap på jobb eller skole'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri hatt en crush på en lærer eller sjef'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri fulgt noen jeg ikke kjenner på Instagram i håp om at de følger tilbake'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri latt noen tro noe galt om meg for å unngå drama'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri spist mat jeg visste tilhørte noen andre'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri brukt andres innloggingsinfo uten å spørre'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri hoppet over treningsøkten og løyet om det'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri vunnet en drikkelek (og vært stolt av det)'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri lagt til noen på Snapchat bare for å se hva de driver med'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri sagt at jeg hadde lest noe jeg ikke hadde lest'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri hatt en lang telefonsamtale der jeg sa alt var bra, men det var det ikke'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri nekt på en date fordi jeg ikke fant dem attraktive nok'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri ønsket meg å bytte liv med noen andre'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri latt meg påvirke av noen andres mening om hvem jeg liker'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri sletta noen fra sosiale medier og angret'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri sov over hos noen og ønsket jeg ikke hadde gjort det'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri sendt en blomst eller gave anonymt'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri prøvd en ny frisyre og hatet den'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri trodd på en konspirasjonsteori'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri vært med på en spontanreise uten å pakke'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri begynt å skrive et innlegg og slettet det'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri angret på noe jeg sa til noen i sinne'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri hatt en samtale som forandret livet mitt'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri falt for noen som ikke visste det'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri blitt nektet inngang på et utested'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri sett på en serie hele natten'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri bestilt mat til meg selv for over 300 kr alene'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri kranglet på sosiale medier med en fremmed'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri tatt en pause fra jobb eller studier for mental helse'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri blitt fortalt at jeg snakker for mye'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri vært med på et slåsskamp'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri bidratt til at noen ble lei seg'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri glemt navnene til alle i et selskap'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri trent naken hjemme'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri hatt en samtale der begge lo til tårer'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri gjort noe bare for å imponere noen'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri meldt meg på noe og ombestemt meg'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri sjekket en annens telefon'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri kranglet over noe helt dust'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri brukt penger jeg ikke hadde på en ferie'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri likt en post fra 3 år tilbake ved en ulykke'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri slutta å følge noen fordi de ble for suksessfulle'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri delt noe privat fra en venn med noen andre'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri ligget i sengen og grublet i timesvis'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri sett på noen romantisk som ikke vet det'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri sagt at jeg forstod noe jeg ikke forstod'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri snakket i søvne'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri falt av en sykkel (som voksen)'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri byttet plass i et fly uten å spørre'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri spist siste stykket uten å tilby det til noen'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri skrevet en negativ anmeldelse online'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri fortalt noen en løgn for å få dem til å føle seg bedre'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri vært til stede på noe uten å ville det'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri latt noen stå for regningen'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri tatt æren for noe noen andre gjorde'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri kranglet med en app-hjelper (chatbot)'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri prøvd å se kjølig ut og mislykkedes totalt'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri forsøkt å imponere noen med en løgn'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri drukket vann og late som det var noe annet'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri oversett en melding fordi jeg ikke visste hva jeg skulle svare'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri blitt forelsket i noen over internett'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri skrevet "haha" uten å faktisk ha ledd'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri hatt en dag der alt gikk galt og lo av det'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri sagt at maten var god selv om den var dårlig'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri latt noen tro de vant en diskusjon bare for å slippe å argumentere'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri sagt "vi ses snart" uten å mene det'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri drukket alene og sett en romantisk film'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri hørt på en sang på repeat i over en time'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri kjøpt en plante og latt den dø'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri prøvd å lage noe fra TikTok og mislyktes'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri stilt et spørsmål jeg allerede visste svaret på'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri later som jeg leste artikkelen når jeg bare leste overskriften'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri angret på en frisyre dag én'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri hatt venner fra veldig ulike deler av livet mitt møtes og det ble litt rart'),
  (jeg_har_aldri_id, 'alle_drikker', '', 'Jeg har aldri glemt hva jeg skulle si midt i en setning');

INSERT INTO kort (spillpakke_id, type, tittel, innhold) VALUES
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å glemme bursdagen til kjæresten?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best i en slåsskamp?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å gjøre noe pinlig på fest?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville klart seg lengst alene på en øde øy?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å ha lest noens meldinger uten å si det?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville blitt rikest om 10 år?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å ha en hemmelig konto på sosiale medier?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært den beste standup-komikeren?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å gråte på en romantisk film?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville overlevd en zombie-apokalypse?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å ringe eks''en full i kveld?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville klart seg best som eneboer i skogen?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest dramatisk i hverdagen?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best som politiker?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å spise den siste biten uten å tilby den?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært verst som romkamerat?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å bli kjendis?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best som overlevelsesinstruktør?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å kaste opp av sjøsyke?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best på baking?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å bli millionær?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best som sjef?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å ha sent noen en melding de angret på?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært dårligst til å holde hemmeligheter?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å forsinke hele gruppen?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville best overlevd en realityshow?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å bli arrestert en dag?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best på reparere ting hjemme?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å ha stalket noen på nett i dag?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best som influenser?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å snorke?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville klart seg lengst uten sosiale medier?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å ha stjålet noe (uansett hvor lite)?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best i krisesituasjoner?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å ta med seg hjem en fremmed fra bar?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best som veterinær?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å si noe feil på en jobbintervju?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville klart seg lengst uten kaffe?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å stikke av fra regningen?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best som vikar i barnehage?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å komme for sent til eget bryllup?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært dårligst som aleneforelder?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å sove gjennom alarmen?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best på å overbevise noen om noe?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å gråte under en reklame?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best som rally-sjåfør?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å ha en hemmelig talentshow-drøm?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært dårligst i en matkonkurranse?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å si noe de angrer på på neste middag?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville klart seg best uten penger i en uke?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å ha en hemmelig selvforbedringplan?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best som standby-psykolog for vennegjengen?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å bli hjerteknuser?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært verst som politiker?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å ha lest CV''ene til folk på LinkedIn?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville klart seg best i en spisekonkurranse?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å falle på is i vinter?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best som forfatter?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å gi bort alt de eier til veldedighet?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best til å navigere uten GPS?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å ha en skjult lidenskap ingen vet om?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville klart seg best i en debatt?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å bestille feil mat og likevel spise det?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best som hjemmekokk for 20 gjester?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å beholde en flaue hemmelighet i årevis?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville klart seg lengst uten seng?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å bli omtalt i en podkast for noe rart?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best til å håndtere en naturkatastrofe?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å ha en crush uten å innrømme det?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best som danselærer?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å glemme å betale en regning?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville klart seg best som munk i et kloster?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å havne på TV i en reality-show?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best som natteravn-frivillig?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å si "bare fem minutter til" og sove i tre timer?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best som etterforsker?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å ha tatt en selfie med en fremmed?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best som personal trainer?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å kjøpe noe dyrt i fylla?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville klart seg lengst på en diett?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å rope noe dumt fra en balkong?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best som megler?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å bli venn med alle på et arrangement?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville klart seg best i Farmen?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å starte en samtale med fremmede på baren?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best som guide på en turreise?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å ha hemmelig dagbok?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært verst til å holde seg rolig under press?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å ha løyet i dag?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville klart seg lengst uten venner?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å bli berømt på TikTok?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best som kirurg?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å si "jeg kan ikke, jeg er opptatt" og bare se på Netflix?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville klart seg best i The Amazing Race?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å vinne en trivia-quiz?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best som bartender?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å ha byttet mening om noe viktig det siste året?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville klart seg best uten internett i en måned?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å glemme nøklene sine hjemme?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best som frilanser?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å ha en plan B for livet?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville klart seg best i en dating-reality?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å ha tatt en impulsreise?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best som DJ på en fest?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å ha en "emergency playlist" for tunge dager?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville klart seg lengst på en øde øy med bare én bok?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å starte et eget firma?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best til å organisere et arrangement?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å si "det var ikke meg" når det var dem?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville klart seg best alene i en fremmed by?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å bruke begreper feil for å virke smart?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best som matlager for hele gjengen?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å holde på en hemmelighet for alltid?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville klart seg best i et hus uten strøm i en uke?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å snakke høyt i søvne?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best som forfatter av en selvbiografi?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å ha googlet noen i gruppen?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville klart seg lengst i stillhet?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å bryte en regel de selv satte?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best som veileder for nybegynnere?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å ha gjort noe galt og ikke sagt ifra?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville klart seg best i en spøkelseshus?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å si ja til alt og så angre?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best som livredder på stranda?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å ha danset alene hjemme i dag?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville klart seg best som journalist?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å ha en klar bucket list?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best på improv-teater?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å bli venn med sjefen sin?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville klart seg lengst uten sukker?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å fortelle en vits som ikke lander?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best som frivillig i utlandet?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å ha meldt seg på et kurs og aldri møtt opp?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville klart seg best på Jeopardy?'),
  (pekeleken_id, 'pekelek', '', 'Hvem er mest sannsynlig å ha mer enn 1000 ulesede e-poster?'),
  (pekeleken_id, 'pekelek', '', 'Hvem ville vært best som politibetjent?');

END $$;
