-- Backfill new kort-felter for existing cards
-- 1. Mark drøy cards (seeded via migrations 00005 + 00009)
UPDATE kort SET droyhet = 'droy' WHERE innhold IN (
  'Hvem er mest sannsynlig til å sende en melding de angrer på i kveld?',
  'Hvem hadde brukt lengst tid foran speilet i dag?',
  'Hvem virker uskyldig, men har egentlig de villeste historiene?',
  'Hvem er typen til å si «jeg tar det rolig» og holde ut i ti minutter?',
  'Hvem kunne fått gratis drinker bare ved å smile til riktig person?',
  'Hvem er mest sannsynlig til å forsvinne fra vorset uten å si fra?',
  'Hvem hadde størst sjanse for å bli kveldens uoffisielle midtpunkt?',
  'Hvem ser ut som de har kontroll, men mister den raskest?',
  'Hvem kunne latt seg overtale til noe dumt bare fordi stemningen var riktig?',
  'Hvem er mest sannsynlig til å flørte seg ut av en pinlig situasjon?',
  'Hvem hadde størst sjanse for å kysse noen de nettopp møtte?',
  'Hvem kunne blitt med på nach bare for historien skyld?',
  'Hvem er typen til å angre på noe før frokost i morgen?',
  'Hvem hadde hatt den mest kaotiske «hvordan skjedde dette?»-forklaringen dagen derpå?',
  'Hvem er mest sannsynlig til å få hele gjengen til å lure på hva som egentlig foregår?',
  'Hvem hadde vært farligst å gi tilgang til andres mobil i to minutter?',
  'Hvem er mest sannsynlig til å bli forelsket i løpet av kvelden?',
  'Hvem hadde klart seg best på en spontan date med fem minutters varsel?',
  'Hvem er minst sannsynlig til å huske hele kvelden i morgen?',
  'Hvem sjekker telefonen mest midt i en samtale?',
  'Hvem er best på å se uskyldig ut etter å ha gjort noe drøyt?',
  'Hvem hadde vært best til å holde en hemmelighet under press?',
  'Hvem er mest sannsynlig til å ta med seg en fremmed hjem i kveld?',
  'Hvem er typen til å si noe de i ettertid ønsker de hadde holdt tilbake?',
  'Hvem hadde klart seg lengst uten å sjekke telefonen?',
  'Hvem er minst sannsynlig til å si nei hvis noen flørter pågående med dem?',
  'Hvem er mest sannsynlig til å ha sendt noen et hjerte de ikke mente?',
  'Hvem hadde vært best til å improvisere en unnskyldning?',
  'Hvem er typen til å ha tre samtaler på gang samtidig på kvelden?',
  'Hvem er mest sannsynlig til å snike seg inn på en fest de ikke er invitert til?',
  'Hvem er best til å få folk til å le akkurat når det passer dårligst?',
  'Hvem hadde klart å overbevise noen om noe som er åpenbart usant?',
  'Hvem er mest sannsynlig til å ha googlet noen i dette rommet?',
  'Hvem er best til å holde ansiktsuttrykket rolig med en løgn?',
  'Hvem hadde vært mest kaotisk å bo med i kollektiv?',
  'Hvem er mest sannsynlig til å glemme hva de lovet i kveld?',
  'Hvem hadde hatt størst sjanse for å ende opp på feil sted til rett tid?',
  'Hvem er typen til å overskride eget budsjett i kveld?',
  'Hvem er mest sannsynlig til å sjekke eksens nye partner på Instagram?',
  'Hvem hadde klart å sove lengst neste morgen?',
  'Hvem er mest sannsynlig til å ha en dating-app åpen på telefonen akkurat nå?',
  'Hvem hadde vært mest effektiv på å skaffe et telefonnummer i kveld?',
  'Hvem er typen til å beklage noe i morgen tidlig?',
  'Hvem er best til å gjøre enhver situasjon litt mer dramatisk enn nødvendig?',
  'Hvem hadde vært farligst å sette i gang på dansegulvet?',
  'Hvem er best til å gjøre en dårlig idé høres fornuftig ut?',
  'Hvem er typen til å komme tilbake fra nach med en ny venn ingen kjenner?',
  'Hvem er mest sannsynlig til å ha et bilde på telefonen de ikke ville vist noen her?',
  'Hvem hadde klart seg best på Tinder med bare ett bilde?',
  'Hvem er typen til å stille opp for alle andre, men aldri si fra om egne ting?',
  'Hvem er mest sannsynlig til å ha en hemmelighet som ville sjokkert noen i rommet?',
  'Hvem hadde vært vanskeligst å bli kvitt etter et nachspiel?',
  'Hvem er minst sannsynlig til å gå hjem alene i kveld?',
  'Hvem er best på å se frisk ut etter for lite søvn?',
  'Hvem hadde brukt pengene villest på en festkveld?',
  'Hvem er best til å sette ord på noe alle tenker, men ingen sier?',
  'Hvem hadde vært farligst å gi tilgang til gruppechatten?',
  'Hvem er typen til å dumpe noen på tekstmelding?',
  'Hvem hadde klart seg best alene i en fremmed by for én natt?',
  'Hvem er best til å se travel ut uten egentlig å gjøre noe?',
  'Hvem er mest sannsynlig til å bli kveldens store overraskelse?',
  'Hvem er typen til å si «jeg er ikke sjalu» og mene det minst?',
  'Hvem er mest sannsynlig til å ha en app på telefonen de ikke vil vise frem?',
  'Hvem hadde klart å flørte seg til gratis taxi?',
  'Hvem er best på å late som ingenting etter noe pinlig?',
  'Hvem er mest sannsynlig til å bli litt for godt kjent med barpersonalet i kveld?',
  'Hvem hadde vært størst innflytelse på gruppen — på godt og vondt?',
  'Hvem er minst sannsynlig til å ta seg hjem til rett tid?',
  'Hvem er best til å få siste ord i enhver diskusjon?',
  'Hvem er typen til å danse uten musikk hvis stemningen er riktig?',
  'Hvem er mest sannsynlig til å ha planlagt kvelden uten å fortelle noen?',
  'Hvem hadde hatt best sjanse for å komme inn på en utsolgt fest?',
  'Hvem er best til å gjøre et dårlig valg høres som en god idé?',
  'Hvem hadde klart seg lengst uten sosiale medier?',
  'Hvem er typen til å bli venn med alle uansett hvem det er?',
  'Hvem hadde vært farligst å la velge musikk for resten av kvelden?',
  'Hvem er best på å lese folk uten at de merker det?',
  'Hvem er typen til å sove med telefonen som klemme-pute?',
  'Hvem er mest sannsynlig til å ha en plan de ikke har fortalt noen om ennå?',
  'Hvem hadde vært best til å redde en pinlig situasjon med en vittig kommentar?',
  'Hvem er minst sannsynlig til å innrømme at de er trøtte?',
  'Hvem er best til å holde ansiktsuttrykket nøytralt når alle andre ler?',
  'Hvem er mest sannsynlig til å ha sjekket eksens Instagram-post i dag?',
  'Hvem hadde klart å få alle på dansegulvet med ett grep?',
  'Hvem er typen til å ha et litt for godt svar klart for enhver anklagelse?',
  'Hvem er mest sannsynlig til å bli den alle snakker om i morgen?',
  'Hvem hadde rotet med feil person og visst det fra starten?',
  'Hvem er mest sannsynlig til å si ja til noe klokken 03 de aldri ville sagt ja til klokken 20?',
  'Hvem hadde hatt størst sjanse for å få noen til å tro de er mer interessante enn de er?',
  'Hvem er best til å gjøre seg utilgjengelig for akkurat den rette personen?',
  'Hvem hadde vært mest sannsynlig til å kysse noen de egentlig ikke burde?',
  'Hvem er typen til å pakke eksen inn i «vi er bare venner»?',
  'Hvem er mest sannsynlig til å starte en inside joke som ingen forstår?',
  'Hvem hadde hatt flest aktive trådsamtaler på en gang uten at noen visste om hverandre?',
  'Hvem er best til å se ut som de ikke prøver, men prøver hardest?',
  'Hvem er typen til å innlede en krangel og fremstå som den fornuftige?',
  'Hvem hadde vært best til å holde tre ting på gang uten at noen merker det?',
  'Hvem er mest sannsynlig til å angre på noe de sa i kveld — men ikke si det?',
  'Hvem er minst sannsynlig til å være den samme personen de var da kvelden startet?'
);

-- 2. Pekelek + Snusboks cards require 3+ players (peking requires group)
UPDATE kort SET min_spillere = 3 WHERE type IN ('pekelek', 'snusboks') AND min_spillere < 3;

-- 3. All cards are active (default), normal drøyhet (default), kjonn=alle (default), vekt=vanlig (default)
-- These are already applied via column defaults; no update needed.
